### ISSUE TITLE
[Bug] German radio backpacks can be put Into the arsenal when you have them as backpack and select another one.

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi-1.4#100]
German radio backpacks can NOT be put into the arsenal when they are in a car/crate and transfer them. Then they vanish.

**Comment by Spoffy** [comment]
Duplicate of #99

**Comment by SonorousMeerkat** [comment]
This expands to include US and probably SOV ones as well. just the radio packs though...

**Comment by Spoffy** [comment]
Fixed in 9895f548fa7b4595577f68c571e8cde560ebb85b
