### ISSUE TITLE
Burning Man has moved to Altis

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi-1.4#103]
Or the AI are suddenly very liberal with their use of smoke grenades.

**Comment by Toakan** [comment]
AI are always liberal with Smokes. As soon as an engagement starts they will pop them out for cover.

**Comment by Spoffy** [comment]
Yeah, gonna close this one was not an issue. It's part of UPSMON if memory serves, and not really an issue, as it doesn't especially harm or enhance the gameplay either way.
