### ISSUE TITLE
initPetros makes the server thread pause whilst spawning objects.

### ISSUE THREAD

**Issue by Toakan** [official-antistasi-community/A3-Antistasi-1.4#105]
https://github.com/official-antistasi-community/A3-Antistasi-1.4/blob/64e3e96eb7f08ab8e233fe0efe4a1e8db3b82988/A3-Antistasi/initPetros.sqf#L82

Keeping Petros invulnerable would be better handled by waiting for the "Mission Load" to complete fully, rather than making this specific script wait for two minutes.

**Comment by wurzel0701** [comment]
Replace the last two line with
```sqf
[] spawn {sleep 120; petros allowDamage true;};
```

**Comment by Toakan** [comment]
Implemented in #107
