### ISSUE TITLE
Don't automatically capture areas when all AI die

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi-1.4#11]

**Comment by wurzel0701** [comment]
Why not? It just will cost time to run towards the flag pole and change the flag. If the AI is dead the place is yours, if not, you can try to get the flag

**Comment by Spoffy** [comment]
I didn't open this issue, I copied from the last repo. Honestly, I'm just gonna close it.

**Comment by SonorousMeerkat** [comment]
While it is closed, i think it was intended as a way to avoid qrf triggering. which i agree is BS
