### ISSUE TITLE
Parameter for mod applied to Soldier uniforms

### ISSUE THREAD

**Issue by Toakan** [official-antistasi-community/A3-Antistasi-1.4#113]
Move the Ammunition/RHSDress.sqf to orgPlayers/Dress.sqf

Create a Parameter for specific MODS.
- RHS
- IFA
- 3CB

Implement switch for mod type, then switch for unit type.

**Comment by CalebSerafin** [comment]
What would be more difficult but easier to maintain is if we have a function that reads through an XML or CSV to get mod assets. But Yes, I do definitely think this is a step in the right direction (no more if-else chains).

**Comment by Spoffy** [comment]
I don't think Arma has any native support for reading and writing files. They should be isolated to the template files, or their own .SQF files, instead. 

Also, I've basically done all of this in e30f6973b64597d5a4836bfb05be62ae96ef8f99, so closing and marking as fixed.
