### ISSUE TITLE
Make non-commander members able to request missions from Petros

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi-1.4#117]
Problem:
Only Commander can get missions of Petros

Wish:
Also other members should be able to get missions from Petros

**Comment by wurzel0701** [comment]
There are ```sqf player == theBoss``` conditions in the dialogs.hpp file, but iirc there are more

**Comment by SonorousMeerkat** [comment]
i do thing

**Comment by Toakan** [comment]
#134  Solved this :D
