### ISSUE TITLE
Move arsenal unlocked items logic to template files

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi-1.4#120]
Right now, it's stopping us adding new mods (or making it harder) as it's embedded in initVar, for seemingly little reason.

**Comment by SonorousMeerkat** [comment]
i mean, the other sides ammobox contents are already defined in the templates. why not this?

**Comment by SonorousMeerkat** [comment]
i guess i can look at this once the initvar cleanup is pulled

**Comment by Toakan** [comment]
Which cleanup are you waiting for @SonorousMeerkat ? #111 has already been merged.

**Comment by SonorousMeerkat** [comment]
Ok then, i'll look at this next

**Comment by SonorousMeerkat** [comment]
Working on this now
