### ISSUE TITLE
Loadout stripping takes first commanders map

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi-1.4#145]
cannot choose other-than-default starting location because starting commander doesn't have a map

**Comment by Spoffy** [comment]
Is this on latest? After I redid RHSDress?

**Comment by PoweredByPot** [comment]
latest as of about an hour ago. I don't use any RHS stuff if it matters.

**Comment by PoweredByPot** [comment]
@Spoffy I see now how close the commit was to my report, I re-updated and will try again.

**Comment by PoweredByPot** [comment]
still an issue on DS
