### ISSUE TITLE
Airfield spawns incorrect

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi-1.4#151]
![image](https://user-images.githubusercontent.com/50651578/63234536-e73b7700-c235-11e9-9db2-f81ac995edc3.png)
As discussed on the 19.08.2019 at 3am your time.

**Comment by Spoffy** [comment]
Fixed today in e2a50093f4c3b2fbb29ba3a44f20c36ef416ebb8
