### ISSUE TITLE
Steal static just despawns the static

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi-1.4#160]
It looks like, from the code, the static is supposed to be replaced with it's component backpacks. However the backpacks almost never spawn in the correct place if at all. could this function be changed to a side reassignment?

**Comment by Spoffy** [comment]
Tweaked in f4f414850f0798405ec3dbb5e0fd6d04f5e150d9, should be fixed. At least, no issues with airfield mortars or tower HMGs
