### ISSUE TITLE
Russian aircraft not spawning correctly [WW2]

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi-1.4#17]
Russian aircraft are spawning at their NW insertion point on the ground, unable to take off. Appears to be bugging paratroop and fighter/fighterbomber attacks

**Comment by wurzel0701** [comment]
https://github.com/official-antistasi-community/A3-Antistasi-1.4/blob/64e3e96eb7f08ab8e233fe0efe4a1e8db3b82988/A3-Antistasi/AI/airstrike.sqf#L100

This is the line would spawn any airstrike 1000 meter above the ground, seems like it is missing somewhere

**Comment by Spoffy** [comment]
After some investigation, I think this might be an issue with CSAT punishment missions. But not 100% certain yet.

**Comment by Spoffy** [comment]
Fixed in 756cef795fd83fc9302cc02cd78b5d4d9ad70590
