### ISSUE TITLE
Fix starting gear missing vests

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi-1.4#176]
Vests seem to have vanished from the unlocked gear on RHSGREF. Possibly others?

**Comment by Spoffy** [comment]
Bug was created in 601f47cc2

**Comment by PoweredByPot** [comment]
already done, will link my fix after meeting

**Comment by PoweredByPot** [comment]
`REBELvests0 = ["V_Rangemaster_belt","V_BandollierB_khk","V_BandollierB_cbr","V_BandollierB_rgr","V_BandollierB_blk","V_BandollierB_oli","V_BandollierB_ghex_F","V_HarnessO_brn","V_HarnessO_gry","V_HarnessO_ghex_F","V_HarnessOGL_ghex_F","V_HarnessOGL_gry","V_HarnessOGL_brn","V_Pocketed_olive_F","V_Pocketed_coyote_F","V_Pocketed_black_F"];`
add to initVar.sqf somewhere around line 625 ABOVE `if !(hasIFA) then`

and then
`unlockeditems append REBELvests0;` WITHIN `if !(hasIFA) then`

**Comment by PoweredByPot** [comment]
@Spoffy added you to make a quick fix while we wait for my PR. Some of this should look familiar to you.

**Comment by Spoffy** [comment]
Fixed in c6d46877c2dfa6ca4a98b10e38f356ce211b52d6
