### ISSUE TITLE
Improve ammo truck mission

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi-1.4#19]
Make the complete requirement based on distance from spawn point/ HQ rather than wether the vehicle is crewed by a player.
Also make the ammo truck variable into an array to allow for multiple options of ammo truck.

This would allow for more variety in the ammo mission as you could be taking a box of ammo (IE rare rockets/weapons) rather than just the ammo truck for vehicle resupply.

(It would also allow for better integration with 3CB, but that is less important)

**Comment by Spoffy** [comment]
Altered in 67b333e7bd29b179ef993d11e5fb24fb135585df

**Comment by PoweredByPot** [comment]
Worked great on vanilla Altis.
