### ISSUE TITLE
PvP side switch delay not working

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi-1.4#202]

**Comment by Spoffy** [comment]
Possible fix in 2e1a0905877afc3ae9bab0836949055798c24871, needs confirming on a dedicated

**Comment by Bob-Murphy** [comment]
PvP switch delay is working.
3600 seconds might be too much.
Could we implement a parameter with 0, 900, 1800, 3600s?

**Comment by Spoffy** [comment]
Sorted in 52f7b45f900e7f125c6b97434b658d812b3c77fa
