### ISSUE TITLE
Update punishment log

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi-1.4#207]
Please add the name and steam ID of the person who got shot to the log file.

**Comment by Bob-Murphy** [comment]
Please also set the _offenceLevel per shot to 0.21 so you need 5 shots until you get punished.
A 3 bullet burst in the torso respectively 1 click with a burst could get you into the punishment and this can happen too easily.

Also, should we think about a _offenceLevel of 0.11 of the person is handcuffed? We just had the situation where PvP players had 2 hostages, the hostages where in a car and blufor was hiding behind the car aka behind the meat-shield. Or should we keep the punishment because they are effectively taken the risk of accidentely shooting their squadmate?

**Comment by Bob-Murphy** [comment]
Could we also track the distance between the two players and maybe even the distance to Petros (or an HQ asset)? This would allow to see if somebody shot somebody close distance at HQ or long distance in the field.

**Comment by Spoffy** [comment]
Done in d2109205580b2ba2b0c4fca4047ce7bebde85c89
