### ISSUE TITLE
PVP overhaul

### ISSUE THREAD

**Issue by SEBArma** [official-antistasi-community/A3-Antistasi-1.4#25]
- [x]  6 pvp slots per side (instead of 8)
- [x]  unlock all vehicles for PVP players when they are civilian (handcuffed), allows captured PVP players to be transported by rebels
- [ ]  new loadouts (when digital is done with bluefor and greenfor)

- [x]  allow PVP players to spawn HMG vehicle
- [x]  unlock HMG humvee and HMG uaz for PVP players depending on side

- [x]  unlock static weapons for PVP players

**Comment by Spoffy** [comment]
Related to #7

**Comment by Bob-Murphy** [comment]
To be able to give PvP players loadouts most certainly a few steps must be implemented:
- The places characters in the mission.sqm must get names like pvp_1, pvp_2 and so on
- make a function that gives the characters the certain loadouts when RHS is active (hasRHS and shit)
- once this is done we also should set up templates for other mods like 3CB-pvp-loadouts

**Comment by Bob-Murphy** [comment]
Changed and renamed slots:

- [ ] Altis GreenFor
- [ ] Altis BluFor
- [ ] Tanoa
- [ ] Chernarus Summer

**Comment by Spoffy** [comment]
This is just waiting on the loadouts now.

**Comment by Spoffy** [comment]
Finished as of 3bde045ba7cf0d49baaeb91c652ac389fabaa3f8
