### ISSUE TITLE
Commander getting stuck on "None"

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi-1.4#27]
This one happens occasionally when automatic commander switch is turned off in the mission parameters. Can be fixed in 1.4 by executing
```
theBoss = player;
publicVariable "theBoss";
```
locally in the debug console, making the player the commander.

**Comment by Spoffy** [comment]
Fixed in unstable (in theory)

**Comment by Spoffy** [comment]
Another bug that causes this fixed in bc12a3839c520e9691d94d8bc2fed9e1e8046e03

**Comment by PoweredByPot** [comment]
copypasta from discord cause i'm sleepy

well it seems to have resolved itself without any intervention
but it occured when swapping from HC to AI direct control trying to reslove stuck units
there were a few times I ended up back in commander but with the short UI
I was still commander though, the UI just seems to have gotten confused
