### ISSUE TITLE
Sleeping bag clip underground when HQ moved/placed

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi-1.4#54]
As above

**Comment by Spoffy** [comment]
Made less likely in 3cafe859b07b6a96773db8545244f021e9f8756e

**Comment by PoweredByPot** [comment]
sorry spoffy, still occurring. 

Happened when loading singleplayer progress (which works flawlessly btw, tasks included). Im going to see if I can re-create on a dedicated server too.

**Comment by PoweredByPot** [comment]
@Spoffy confirmed this is still occurring on dedicated servers

**Comment by Spoffy** [comment]
Yeah, I made it less likely, didn't really fix it. The fix is probably to replace the sleeping bag with something else - it's too thin. 

I am a little surprised it's happening so easily though - it's set to spawn floating a bit above the ground. Is it completely clipping under, or only partially?
