### ISSUE TITLE
[SP] Killing CIV units

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi-1.4#57]
Was awarded 20 credits when a CIV ran in front of my car, instead of being penalized 1 Aggression. I will keep watching to see if it was coincidence or a true error.

**Comment by PoweredByPot** [comment]
confirmed, mowing down civvies in singleplayer is a pretty reliable source of income, with no negative consequences.

**Comment by Spoffy** [comment]
Doesn't aggression go up?

**Comment by PoweredByPot** [comment]
negative, just a payday without any penalty

**Comment by Spoffy** [comment]
Totally fixed in 18af24de5fd67a01991ccf9f6b1ddb4ece85d157 and 6130237a194c5b1d1c47120c81ff3be2a2d6aa36
