### ISSUE TITLE
[Low Priority] Author does not fit textfield

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi-1.4#59]
Seems like the author name is a bit to long to be displayed correctly. Either shorten the name or make the text field larger

![TitleBug](https://user-images.githubusercontent.com/31988396/62542933-1c6ebf00-b85d-11e9-96ea-96e3ab7c5df7.jpg)

**Comment by Toakan** [comment]
This cannot be changed unfortunately, however moving to the credits.sqf based system should remove the issue.

@Bob-Murphy do you want to close this as fixed with #92 ?

**Comment by Bob-Murphy** [comment]
Closed with #92
