### ISSUE TITLE
Bleach the "asshole" code

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi-1.4#60]
Inactive code in the description.ext line 420-ish and stuff related to that

`    /*
    class asshole
    {
        title = "Forbidden";
        subtitle = "You are not allowed to run Antistasi";
        description = "Sorry, but you cannot play Antistasi in your server. Please contact author to discuss your situation.";
        picture = "b_unknown";
        pictureColor[] = {0.0,0.5,0.0,1};
    };
    */`

**Comment by Bob-Murphy** [comment]
Edited name of the issue from "Delete the asshole code" to Bleach the asshole code".

**Comment by Spoffy** [comment]
Thoroughly bleached in 398bed2bc66d1a53af36da0779d5d614d5697e4c
