### ISSUE TITLE
Arsenal Notification Inconsistency

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi-1.4#66]
I've noticed that sometimes dropping enough of something to unlock it in the arsenal causes an immediate pop-up that says "Arsenal: Xweapon was unlocked".

But other times It doesn't say anything until the tax loop. I know that tax loop and save loop will convert items that are over the unlock limit to unlimited, but IDK if the other intermittent message does it.

**Comment by PoweredByPot** [comment]
I just now saw it trigger on one gun that got put over the limit but not another, both loaded at the same time. Definitely not expected behavior.

**Comment by Spoffy** [comment]
There's only a few places in the code where this updating - Periodically by the server, during persistent save, during initial startup, and during transfer to ammobox. I'm not actually sure this is a bug - it's probably just be a coincidence you hit the right timing/circumstances to trigger an update.

**Comment by PoweredByPot** [comment]
to be clear it is not part of the tax loop, no money or HR is awarded, tasks don't update.

Just 'HEY you unlocked this gun, (but don't worry about those other ones).'

**Comment by Spoffy** [comment]
Yeah, it updates if you use 'Load Ammobox' I think, too.

**Comment by PoweredByPot** [comment]
one thing I can say is that it should be a unique string because the text size is flippin enormous. Just one gun and its ammo, and the word 'ARSENAL' take up the whole bottom right, it's much larger than tax loop text.
