### ISSUE TITLE
[SP] Arsenal tabs for explosives and grenades are blank

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi-1.4#67]
If you select your vest/uniform/backpack in the arsenal and choose the right-hand tabs for "explosives" and "grenades" are completely empty.

**Comment by PoweredByPot** [comment]
both categories are visible if you select the "magazines" tab

**Comment by Spoffy** [comment]
Urgh, good catch.

**Comment by Spoffy** [comment]
Fixed in 4578e8090f445796c6f324ad415be09f7ff22ecd

**Comment by PoweredByPot** [comment]
sorry bud, didn't fix it yet

**Comment by Spoffy** [comment]
Try loading a new save, you may find that totally sorts it.

**Comment by PoweredByPot** [comment]
you are correct, disregard
