### ISSUE TITLE
Dead bodies of disconnected players litter HQ

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi-1.4#76]
I have no idea what the cause is, but this was reported by at least one other player, and I already know the fix (a fix).

give me a few moments and I will put up a pull request.

**Comment by Toakan** [comment]
+1 Seeing this on unstable.

**Comment by Spoffy** [comment]
Looks like it's an issue with onPlayerDisconnect not being able to delete the unit when deleteVehicle is called. Delaying the call by 10 seconds sorts the issue out, but isn't the right solution. Should be able to patch it out tonight.

**Comment by Spoffy** [comment]
Fixed in e4519ffbd1c797c8042a19d5d789d55494052d9d
