### ISSUE TITLE
Petros damage is reseted once any player shoots him

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi-1.4#82]
https://github.com/official-antistasi-community/A3-Antistasi-1.4/blob/d1a38050b0756b098064b5ae174db752fa17f8ef/A3-Antistasi/initPetros.sqf#L15-L18

This line does not nullifies the incoming damage but setting the overall damage of this body part of Petros back to 0. So, in theory, you should be able to keep Petros from dying if you have a mg and just spray him. As long as you do this he will be healed again and again, so the enemy forces can't kill him

**Comment by Toakan** [comment]
Potential code fix?
Prevents immunity reset and allows enemy a way to kill Petros.
```
if ((isPlayer _injurer) && {side _injurer == side petros})
    {
    _dam = _dam - 0.01;
    };
```

**Comment by wurzel0701** [comment]
`if ((isPlayer _injurer) && {side _injurer == side petros})
{
    _dam = (_this select 0) getHitPointDamage (_this select 7);
};`
This should do it
