### ISSUE TITLE
Misc Items aren't unlocking

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi-1.4#85]
The laser may be because of the wrong category thing, but I would think both should eventually unlock.

**Comment by PoweredByPot** [comment]
also, medikits and toolkits occasionally spawn in crates as loot, but start the campaign unlocked. Both items should be removed from the loot list.

**Comment by Spoffy** [comment]
Yeah, nothing in misc unlocks apparently.

**Comment by Spoffy** [comment]
Laser is correctly classified in 4e4b64202386e9244eaa2a355ab2520b35fc289b

**Comment by Spoffy** [comment]
Not solving the 'misc doesn't unlock' issue in this release - too much risk that it messes with something. I also think it may need discussing.
