### ISSUE TITLE
Re-Implement the HQ grenade shield

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi-1.4#89]
HQ used to have a system in place that blocked people from throwing grenades with either Ace advanced throwing or base game grenade throw.
Lets bring this back and make sure the zone moves with HQ.

**Comment by Toakan** [comment]
@SonorousMeerkat Are you sure this is an issue? On unstable vanilla i'm currently unable to throw grenades anywhere near Petros.

I can however fire rockets, so that will need fixing.

**Comment by wurzel0701** [comment]
The grenade shield is there, still in place

https://github.com/official-antistasi-community/A3-Antistasi-1.4/blob/64e3e96eb7f08ab8e233fe0efe4a1e8db3b82988/A3-Antistasi/initPlayerLocal.sqf#L50-L64

It cannot shield against rockets currently, but it would be possible to implement this. The zone should also move with Petros

**Comment by Toakan** [comment]
Changing the event handler to "FiredNear" may be an easier way to do this.  We can then prevent any friendly actions near Petros.

One bug however, this currently prevents players from using Smoke Grenades near Petros, which could be useful during a Defence mission.

**Comment by wurzel0701** [comment]
Some goes for missiles, you propably want some AA missile ready once the HQ is under attack

**Comment by Spoffy** [comment]
Fixed in 96b98cf71ca7932f53fa8adaa2a0d8a13c5147b2. It'll only affect grenades and explosives, not missiles. 

Issue details: ACE throwables/placeables weren't calling vanilla event handlers.
