### ISSUE TITLE
Punishment.sqf implementation

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi-1.4#91]
Re-implement punishment.sqf so that it triggers properly on player respawn after being tagged with tkpunish for excessive civilian kills / friendly fire.

Also have it trigger directly on a player who kills petros while on his side.

**Comment by SonorousMeerkat** [comment]
Also push the name and UID of the player who is punished to the .RPT file.

**Comment by CalebSerafin** [comment]
I'll close this issue as soon as `Punishment.sqf is now called appropriately v2` is merged.

**Comment by Spoffy** [comment]
Closed in #175
