### ISSUE TITLE
[BUG] Static wep on output structures can't be manned by AI

### ISSUE THREAD

**Issue by kiakri** [official-antistasi-community/A3-Antistasi-1.4#94]
*Version:* 1.4c1.04

*Mods:* Vanilla

*Environment*: MP Hosted

*.rpt attatched?* no

*have you edited the missionfile?*: No

***Issue:***
When deploying static weapons at output if you put them into the green structures they aren't counted on the garrison so riflemen will not mount them.

All static weapons need to be placed on ground level.

---

The server is owned by Tad and can provide any files needed

**Comment by SonorousMeerkat** [comment]
Possible change could be to make garrisons use any static placed within the marker area used for detection and flag placement etc.

**Comment by Toakan** [comment]
Doing that would let you build custom extended roadblocks or outposts with static AA / AT points also. This could provide more benefit / reason to the players to make use of statics.

You could also use this to take over enemy roadblocks and their statics, so long as you've "Stolen" them first?

**Comment by kiakri** [comment]
The statics are designed in that way, unless you unpack and repack they disappear on next restart. 

Like the idea of placing static AA / AT at roadblock because AT/AA trucks ate fucking useless they just get obliterated by jets

**Comment by Spoffy** [comment]
Fixed in 281cd2a2bc2a17075a9318e329c463ba97718854
